web/django/05_AUTH/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('force_logout/', views.force_logout, name='force_logout'),
]

web/django/05_AUTH/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('contact/', views.contact, name='contact'),

    path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),

    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),

    path('<int:article_pk>/edit/', views.edit, name='edit'),
    # path('<int:article_pk>/update/', views.update, name='update'),

    path('<int:article_pk>/delete/', views.delete, name='delete'),

    # 댓글 작성
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),

    # 댓글 삭제
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

web/django/05_AUTH/auth_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

web/django/05_AUTH/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articles:index' %}">My App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'articles:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'articles:new' %}">New</a>
        </li>
        <li class="nav-item dropdown">
          {% if user.is_authenticated %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:profile' request.user.username %}">MyPage</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
          {% else %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Who Are You?
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Signup</a></li>
          </ul>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

web/django/05_AUTH/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <title>My app</title>
</head>
<body>
  {% comment %} 
    DTL 예약 변수명 (View 에서 넘겨준 Context 가 없어도 동작)
    - request (요청관련 내용)
    - request.user (현재 요청을 보낸 사용자에 대한 내용)
    - user => request.user 의 줄임말(shortcut)
  {% endcomment %}
  {% include '_navbar.html' %}
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>