web/django/05_AUTH/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('force_logout/', views.force_logout, name='force_logout'),
]

web/django/05_AUTH/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('contact/', views.contact, name='contact'),

    path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),

    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),

    path('<int:article_pk>/edit/', views.edit, name='edit'),
    # path('<int:article_pk>/update/', views.update, name='update'),

    path('<int:article_pk>/delete/', views.delete, name='delete'),

    # 댓글 작성
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),

    # 댓글 삭제
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

web/django/05_AUTH/auth_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

web/django/05_AUTH/articles/models.py
from django.db import models

class Article(models.Model):
    # ORM 은 models.py 내부의 class 에서, class var 만 확인하여 DB의 Column으로 만든다.
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} => {self.title}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

web/django/05_AUTH/articles/forms.py
from django import forms
from .models import Article, Comment
"""
Why Form?
1. Data Validation
2. HTML easy
"""

# forms.Form => 특정 모델과 연동 X 단순히 데이터 검증/HTML생성용
class ContactForm(forms.Form):
    name = forms.CharField(min_length=2, max_length=5)
    email = forms.EmailField()
    age = forms.IntegerField(min_value=3, max_value=100)
    content = forms.CharField(widget=forms.Textarea)  # widget => HTML 생성시 주는 옵션


class ArticleForm(forms.ModelForm):
    # title = forms.CharField(min_length=1)
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('article',)

web/django/05_AUTH/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ContactForm, ArticleForm, CommentForm

"""
1. 사용자가 /crud/contact/ 로 접속 => GET /crud/contact/
2. 사용자가 HTML > form 에서 데이터 제출 => POST /crud/contact/
3. view 함수에서 contact 로 redirect 시킴 => GET /crud/contact/
""" 
def contact(request):
    if request.method == 'GET':
        contact_form = ContactForm()
        context = {'contact_form': contact_form}
        return render(request, 'articles/contact.html', context)
    elif request.method == 'POST':
        contact_form = ContactForm(request.POST)  # {name: 'dsklfj', email: 'aslkdjfl', content: 'asdfkjl'}
        print(contact_form.is_valid())
        print(contact_form.errors)
        return redirect('articles:contact')


@login_required  # not logged_in 일 경우에, 무조건 '/accounts/login/' 으로 redirect 한다.
@require_http_methods(['GET', 'POST'])  
def new(request):
    # 사용자 요청이 GET일 경우
    if request.method == 'GET':
        # 비어있는 새로운 form 생성
        form = ArticleForm()
        context = {'form': form}
        # HTML 에 form 실어서 전송
        return render(request, 'articles/new.html', context)
    
    # 사용자 요청이 POST일 경우
    elif request.method == 'POST':
        # form 에 요청 DATA 를 입력
        print(request.POST)
        form = ArticleForm(request.POST)
        # form 을 통해 DATA 유효성검사(validation)
        if form.is_valid():
            # 유효하다면, 저장
            article = form.save()
            # 저장한 article 의 상세보기 페이지로 redirect
            return redirect('articles:detail', article_pk=article.pk)
        else:
            # 유효하지 않다면, 기존의 잘못된 DATA 를 담은 form(L34)을 담고
            context = {'form': form}
            # HTML 에 실어서 전송
            return render(request, 'articles/new.html', context)


def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
        }
    return render(request, 'articles/detail.html', context)


def edit(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if request.method == 'POST':
        # new 와 다르게, 특정 article 에 대한 내용을 request.POST 로 덮어 쓰기.
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    elif request.method == 'GET':
        # 기존 게시글 내용을 포함한 HTML 을 만들기 위해 instance 추가
        form = ArticleForm(instance=article)
    
    context = {'form': form}
    return render(request, 'articles/edit.html', context)


def delete(request, article_pk):
    return redirect()
    
@require_POST
def comments_create(request, article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'comment_form': comment_form,
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def comments_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

web/django/05_AUTH/articles/templates/articles/contact.html
{% extends 'base.html' %}
{% block content %}
<h1>CONTACT</h1>
<form action="{% url 'contact' %}" method="POST">
  {% csrf_token %}
  {{ contact_form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

web/django/05_AUTH/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Detail</h1>
<h2>{{ article.pk }} : {{ article.title }}</h2>
<p>{{ article.content }}</p>
<div>
  <a href="{% url 'articles:index' %}">INDEX</a>
</div>
<div>
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a>
</div>
<hr>
<h4>댓글 목록</h4>
<ul>
  {% for comment in comments %}
    <li>
    {{ comment }}
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method='POST'>
      {% csrf_token %}
      <input type="submit" value='DELETE'>
    </form>
    </li>
  {% endfor %}
</ul>
<form action="{% url 'articles:comments_create' article.pk %}" method='POST'>
  {% csrf_token %}
  {{ comment_form }}
  <input type="submit" value="댓글작성">
</form>
{% endblock content %}

web/django/05_AUTH/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit</h1>
{% comment %} 
1. 이 html 을 받아보는 중이라면, request => GET /articles/edit/
2. 아래 제출버튼을 누른다면, action 은 자동으로 위의 URL을 사용 + method POST
   결론: request => POST /articles/edit/
{% endcomment %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

web/django/05_AUTH/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Index</h1>
<div>
  <a href="{% url 'articles:new' %}">NEW</a>
</div>
<ul>
  {% for article in articles %}
    <li>
      <a href="{% url 'articles:detail' article.pk %}">
        {{ article.title }}
      </a>
    </li>
  {% endfor %}
</ul>
{% endblock content %}

web/django/05_AUTH/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1>New</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}